module cli;

import std.stdio, std.format;
import config;

void showHelpMessage()
{
    writeln("Usage: eureka <file.ek> [options]");
    writeln();
    writeln("Options:");
    writeln("  -v, --version    Show language version");
    writeln("  -h, --help       Show help message (this message)");
    writeln("  -L               Shares symbols from '.so' and '.dll' files with the interpreter");
    writeln("  --ast            Shows the AST generated by the program (debug)");
    writeln("  --tokens         Shows the tokens generated by the program (debug)");
    writeln("  --context        (debug)");
    writeln("  --stat           (debug)");
    writeln("  -o, --output     Saves the IR or BIN to a specific file");
    writeln("  --repl           Enter language repl mode");
    writeln();
    writeln("Examples:");
    writeln("  eureka hello.ek");
    writeln("  eureka hello.ek --ast");
    writeln("  eureka hello.ek --tokens");
    writeln("  eureka hello.ek --tokens --ast");
    writeln("  eureka examples/print.ek -L stdlib/lib.so -L stdlib/iolib.so --stat");
    writeln("  eureka --repl");
}

void showVersion()
{
    writefln("%s - v%s\n» %s", NAME, VERSION, DESC);
}

string getFileSource(string file)
{
    File file_ = File(file, "r");
    size_t len = file_.size;
    char[] buff = new char[len];
    file_.rawRead(buff);
    file_.close();
    return cast(string) buff;
}

void setFileSource(string file, string source)
{
    File file_ = File(file, "w");
    file_.rawWrite(source);
    file_.close();
}
